// src/components/ui/input.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

export interface InputProps
    extends React.InputHTMLAttributes<HTMLInputElement> {}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
    ({ className, type, ...props }, ref) => {
        return (
            <input
                type={type}
                className={cn(
                    "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-base ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
                    className,
                )}
                ref={ref}
                {...props}
            />
        )
    },
)
Input.displayName = "Input"

export { Input }

// src/components/ui/input/Input.vue
<script setup lang="ts">
    import type { HTMLAttributes, InputHTMLAttributes } from "vue"
    import { cn } from "@/lib/utils"
    import { useVModel } from "@vueuse/core"

    const props = defineProps<{
        defaultValue?: string | number
        modelValue?: string | number
        class?: HTMLAttributes["class"]
        type?: InputHTMLAttributes["type"]
        placeholder?: InputHTMLAttributes["placeholder"]
        id?: InputHTMLAttributes["id"]
        name?: InputHTMLAttributes["name"]
    }>()

    const emits = defineEmits<{
        (e: "update:modelValue", payload: string | number): void
    }>()

    const modelValue = useVModel(props, "modelValue", emits, {
        passive: true,
        defaultValue: props.defaultValue,
    })
</script>

<template>
    <input
        v-model="modelValue"
        :class="
            cn(
                'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
                props.class,
            )
        "
    />
</template>
